DEFAULT_REQUEST_TIMEOUT_IN_SECONDS = 5.0
DEFAULT_METRICS_UPDATE_TIME_IN_SECONDS = 3600.0
DEFAULT_UPDATE_RETRIES_MAX_AMOUNT = 5
DEFAULT_UPDATE_RETRY_TIME_IN_SECONDS = 5.0
DEFAULT_LOGGING_FORMAT = '%(asctime)s - %(levelname)s - %(message)s'
